### Create New Task
POST http://localhost:8080/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlzcyI6IlRPRE8tQVBQIiwiaWF0IjoxNzE3NDEyNzI3LCJleHAiOjE3MTc0MTM5Mjd9.xbiKGquOgnywtPT9ulEO2QDUCfYHv0Ou4fNUULigKJs

{
  "title": "Bu bir yapılacak maddesidir!"
}

### Get All Tasks
GET http://localhost:8080/tasks?pageNumber=0&pageSize=5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlzcyI6IlRPRE8tQVBQIiwiaWF0IjoxNzE3NDEyNzI3LCJleHAiOjE3MTc0MTM5Mjd9.xbiKGquOgnywtPT9ulEO2QDUCfYHv0Ou4fNUULigKJs

### Get a Task by Id
GET http://localhost:8080/tasks/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcxNjY1NjUyNiwiZXhwIjoxNzE2NjU3NzI2fQ.gwCKeI14E8NIFYtYJ_IETujZ2n8X4xRJCSev273hQao

### Update a Task using UpdateTaskRequest as the body
PUT http://localhost:8080/tasks/1
Content-Type: application/json

{
  "title": "Deneme Task'ı Yaptım ve PUT kullandım",
  "completed": true
}

### Patch a task's completed value usin UpdateTaskCompletionRequest as the body
PATCH http://localhost:8080/tasks/1
Content-Type: application/json

{
  "completed": false
}

### Delete a task by id
DELETE http://localhost:8080/tasks/5

### Authenticate
POST http://localhost:8080/authentication
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

### Me
GET http://localhost:8080/authentication/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlzcyI6IlRPRE8tQVBQIiwiaWF0IjoxNzE3NDEyNzI3LCJleHAiOjE3MTc0MTM5Mjd9.xbiKGquOgnywtPT9ulEO2QDUCfYHv0Ou4fNUULigKJs